apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-service
  template:
    metadata:
      annotations:
        gitops.sentinel/incident-id: inc-1786795864-91811809
      labels:
        app: demo-service
    spec:
      containers:
      - env:
        - name: FEATURE_FLAG_X
          value: 'false'
        image: kennethreitz/httpbin:previous
        name: demo-service
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
